repos:
  # Formatiert den Code automatisch bei jedem "commit"
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        stages: [pre-commit]

  # Testet den Code automatisch bei jedem "push"
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
